server:
  port: 10086
logging:
  config:
  classpath: logback.xml

spring:
  application:
    name: neo-ratelimit
  redis:
    host: 127.0.0.1
    port: 6379
    password:     # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
#    cluster:
#      nodes:
#        - 192.168.2.121:7000
#        - 192.168.2.122:7000
#        - 192.168.2.123:7000
#        - 192.168.2.121:7001
#        - 192.168.2.122:7001
#        - 192.168.2.123:7001
