#服务名称
spring:
  application:
    name: customer-server
#服务启动端口
server:
  port: 10093
logging:
  config: classpath:logback.xml


#主机地址
eureka:
  instance:
    prefer-ip-address: true #优先使用ip地址的方式注册
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true #服务健康检查
    #服务地址
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka/

feign:
  hystrix:
    enabled: true #开启熔断


