server:
  port: 10088
logging:
  config:
    classpath: logback.xml

tio:
  websocket:
    server:
      # websocket port default 9876
      port: 8888
      # 心跳时间 单位ms
      heartbeat-timeout: 600000
      # 自动注入 默认关闭 不开的话需要给handle 加@Service
      use-scanner: true
      # 集群配置 默认关闭
    cluster:
      enabled: false
      # 集群是通过redis的Pub/Sub实现，所以需要配置Redis
      redis:
        config-path:
        ip: 127.0.0.1
        port: 6379
      all: true
      group: true
      ip: true
      user: true
    # SSL 配置
    ssl:
      enabled: false
      key-store: test
      password: test
      trust-store: test